### ISSUE TITLE
vim's background change to grew

### ISSUE THREAD

**Issue by XiaochenCui** [agude/eldar.vim#2]
This is my screenshot of vim : ![](https://lh3.googleusercontent.com/ae50Z-t0TRzpU9vjihar6SckWBZCEQnLUVkquKSg5vJDQD-XH2javLZG_8qTaeRgOFqFPVyANR_tGmswB3cQMOypAIe8yQznZnrJtnMUByydrXpNa9D7CWdWZ9Ja1JKJwsw_KD6sk7QoNdZZHLYHZp8pCqicodRrbGEgqBOOl6WZYOn35HXx6Jtn5wQGe7nlAuHgByXr4Cl-4FL7r5RJ-mUb2PsBeSeJbSoOB-efN7lN4QZcz_RdCTrYrRg4mfHrsOXXBrG0U49uj6leJSXzbt0K5B5IR8SqNAEVI1LMT1JzRLyS9W1F5pDmSmg4Etcw4pVtcdY5JCyBWhEUVy-zE4EtWjA6ihQsCzocRP2NMTFs4rX7vwmSrxuhSjJ-Km-v480LBj_gb5vCc-I_n-829R0MToEw1WKbCLhT495Wtl9-5pvntZ7LNsNo1aT3ZMUIk-X2NUh0pTcm142EKxGdgUgEaZWOTQrjluaCf7qidyjc9fgQeo-bTmVDPjw0mKEKKdGSh30NHinZs98axhRz1d4eJt2_9svsAgqxpK2G6shMmpwRk6SsjJuZ9lSUDpF46ulLjgRM0FU8lgtUt3YYhrqVFM5LRdybY17vWD7RBhcb41XjNvfK=w1160-h652-no)
Vim become grew instead blank after install eldar.

**Comment by agude** [comment]
Hi @XiaochenCui:

I can't see your image, but I suspect it is because of [this line](https://github.com/agude/vim-eldar/blob/master/colors/eldar.vim#L87):

```viml
let  s:ColourAssignment['Normal']        =  {'GUIFG':  'White',     'GUIBG':  'Black'}
```

That hard-codes the text color to white and the background color to black. I did this because I was forced to use a terminal with a weird background in the past, but I don't think it is required anymore (certainly I don't have to use that terminal anymore!). I'll turn it off and add a flag to turn it back on.

Expect a patch tonight!

**Comment by XiaochenCui** [comment]
Hi @agude:

I tried remove that line and changed background color to blank successily.
So I create a [pull request](https://github.com/agude/vim-eldar/pull/3).

Now it looks like:
![](https://lh3.googleusercontent.com/Ui45puucdqQdvJWshWpcU4-DFqRtRVTG0noRpBx70eMFYHS5iaczLB6kO9GpfzHDw0GkijOs3qi8IAPyghEHlUdn_SO6dG5l_mpgyLS34QKeTttTadVAKy_j2VZTWE64xari7npohwIqPyKV0-Ah3aDuhkvSRHkoVO2CAN1ro3hjtfTEoZs6gAV5srcO3C6Poy8b-aWUgGBBNSpPekQPpnF_rxAWJKX07Qh4ssEjo1X7wzSxal7PkPqepeV-M1p6qZvxw4J0Amg52_8AvlK2xG0URyql2-pJ-hEgkSU1fblb_wYDebW77dyCdJ4cKFjq0W3t4vdbEcwvjCnuPLungZeEyr00WmzV512YQUe6ttbPDcWDKq5UrnZ_7wpxoGHJcfBSOt_QxtnWTbAXzdJwHjdbkBRuOxBIhdmqwbsfK1Og1EMRnv5ms1pHGxVrJRxuTst4f_DMiVdI7foDvO-O8Iub-1jocmnb9bS9hkE1rx7vydOjtVArhMp_ebRi3S6RGnsjnoGIUsY62owIKwEYf4ujkxOwybBz0BpDRRe-X2INafYaEBFi8ER4sSoxw8ugeygAXCsuEINpSHKXQcGEVyjcYUft2pNFbAJCbQAOsp6pp8UUhyL3=w1160-h652-no)
