### ISSUE TITLE
How to change line number's color?

### ISSUE THREAD

**Issue by XiaochenCui** [agude/eldar.vim#4]
After I changed the background image in terminal, the line number can't been recognition clearly. Like below:
![screenshot](https://lh3.googleusercontent.com/NJJ8_BJBlLk0iW8JEJa0agif7lujj_rkvBqg4r789Cu5TVzITrK5SuNuBMTnVdi5Ea4_NLK2VTFSoXNBuW9z53owsm5XzDiH3uY_bymX7MESlajup5E_Nlva5fDz7VVe32vUK67DFAuZX3LWVFIEkKNf0obzZVzv7lyo_vozQ77yPAMC8pdz3PEJ-1K_JqRq8T7KGFId0OdyibLQ_KJggcvsnhdgI76Mn_Nzfx-PSphLjxZyBVyRmwdkYBeHusjiycKfiCK9xWog7yNCYpeFGfVbG_CTuXoSg9TqMPuFQa-g5MLAkvT3cTlR9LP4lMeSw3RxHnr29hWhaC3icxzEx8cnhk-Tj1ZVw4TIn6Wd_cDewUP8XvdMxvmrWQ3mpANmXl94hLg2_QoXBq8I--TrMpnM2WsnNWL4Q_Y98wtRUNLDeEkR_jZg37ctTxIjaYLHn2TywdJl4DbcDUhWqfUwwsOPnN2cYl7H1s2sb4Bq44mFiXvFigvbN5AVHyDQT5gEfHTH7QjJxpcxgfyU8pX8MsrIdnbqw1GxrVnlztxwbdU1367SATANWlI4lU3MjbwaoiJmje4QSFp0LPUdnamWKurYepf8pewenXC6WSRKshKb6kL2pwom=w1160-h652-no)

How can I change the color of the line number? Thanks.

**Comment by agude** [comment]
There are two highlight groups you'll need to change (well, just one if you don't use `cursorline`). `LineNr` sets the color for the numbers, and `CursorLineNr` sets the color for when you have `:set cursorline` enabled. You can do this in two ways. I prefer the first (`vimrc` override method) method because it won't conflict with any future changes to the color scheme, but both will work.

## Override the specific colors in your `vimrc`

Override in your `.vimrc` (or `init.vim`) by putting `autocmd ColorScheme * highlight ...` calls just above where you set `colorscheme eldar`, as per [StackOverflow](https://stackoverflow.com/a/7383051):

```vim
if has('autocmd')
    augroup coloroverride
        autocmd!
        autocmd ColorScheme * highlight LineNr  ctermfg=DarkGrey guifg=DarkGrey " Override LineNr
        autocmd ColorScheme * highlight CursorLineNr  ctermfg=White guifg=White " Override CursorLineNr
    augroup END
endif
silent! colorscheme eldar " Custom color scheme
```

## Edit the color scheme directly

Edit `eldar.vim` and change these lines:

```vim
let  s:ColourAssignment['LineNr']        =  {'GUIFG':  'DarkGrey'} "
let  s:ColourAssignment['CursorLineNr']  =  {'GUIFG':  'White'} "
```

----

In both cases you'll want to replace DarkGrey and White with your preferred colors.

**Comment by XiaochenCui** [comment]
@agude Thanks
